### ISSUE TITLE
You can go ahead and add your article to the README file of the Xray project.

### ISSUE THREAD

**Issue by chika0801** [SasukeFreestyle/XTLS-Iran-Reality#1]
https://github.com/XTLS/Xray-core#usage

Tutorial
[XTLS Vision](https://github.com/chika0801/Xray-install)
[REALITY (English)](https://cscot.pages.dev/2023/03/02/Xray-REALITY-tutorial/)

This way, your articles can be found by more people who need help.

**Comment by RPRX** [comment]
Added.
