### ISSUE TITLE
invalid character '.' in string escape code

### ISSUE THREAD

**Issue by houmie** [SasukeFreestyle/XTLS-Iran-Reality#14]
Hello my friend,

I've found a new issue.  A fresh installation on Debian 11.

This shows up in Syslog:
> Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf/serial: failed to decode config: /usr/local/etc/xray/config.json > infra/conf/serial: failed to read config file at line 1982 char 27 > invalid character '.' in string escape code

This [line](https://github.com/SasukeFreestyle/XTLS-Iran-Reality/blob/8daaaf7105b6368da96959f4c6ff870193f5521f/config.json#L1982C16-L1982C34) is affected.

I asked ChatGPT and it said it should be like this:
`"regexp:.*\\.ir$",`

After I fixed it like that, it works.

What do you think?

**Comment by houmie** [comment]
Oh and one more thing that looks suspeciously wrong.

The 5 lines underneat, have no TLD (like .com or .ir):
```
               "snapp",
               "digikala",
               "tapsi",
               "blogfa",
               "bank",
```

Is this an oversight?
Thanks

**Comment by SasukeFreestyle** [comment]
> I asked ChatGPT and it said it should be like this: `"regexp:.*\\.ir$",`
> 
> After I fixed it like that, it works.


The one you posted is exactly the same as [line](https://github.com/SasukeFreestyle/XTLS-Iran-Reality/blob/8daaaf7105b6368da96959f4c6ff870193f5521f/config.json#L1982C16-L1982C34)

`"regexp:.*\\.ir$",`

![image](https://github.com/SasukeFreestyle/XTLS-Iran-Reality/assets/2391403/0c7d1ab6-7258-40aa-922b-302aa8ccadd3)

> Oh and one more thing that looks suspeciously wrong.
> 
> The 5 lines underneath, have no TLD (like .com or .ir):
> 
> ```
>                "snapp",
>                "digikala",
>                "tapsi",
>                "blogfa",
>                "bank",
> ```
> 
> Is this an oversight? Thanks

This is from Iranxray repo 
https://github.com/iranxray/hope/blob/main/routing.md?plain=1#L249

https://github.com/iranxray/hope/blob/main/routing.md#%DA%AF%D8%A7%D9%85-%D9%BE%D9%86%D8%AC%D9%85-%D8%A7%D8%AE%D8%AA%DB%8C%D8%A7%D8%B1%DB%8C

**Comment by houmie** [comment]
Apologies, you are right.  Something has happened when I copied your config to my VPS.  Now I'm worried that I messed it up somewhere else too. I better start from beginning to be sure. 

Thank you for the explanation. It seems it accepts a partial name too instead of full domain with TLD.  Exciting. :)

**Comment by SasukeFreestyle** [comment]
No problem friend.
