### ISSUE TITLE
Two IPs might not be in Iran

### ISSUE THREAD

**Issue by houmie** [SasukeFreestyle/XTLS-Iran-Reality#15]
Hello I have checked every IP in your list and they look good.  But I discovered two IP addresses that might be not Iranian.
But I'm not sure if these companies work for Iran or not.

IP 91.186.201.0/24 is in country AU
IP 194.87.23.0/24 is in country DE

I just thought I'd mention it here.
Thank you

**Comment by SasukeFreestyle** [comment]
Hi!

You are correct on the CIDR 194.87.23.0/24

However, I'm getting multiple different results when searching for 91.186.201.0/24 Both AU and IR
It all depends on what service/website you use and how updated the database is.

Also sometimes CIDR's change and maybe locate to another provider in an another country, And I've honestly not checked the CIDR list for many months 😂

I will remove 194.87.23.0/24 but will keep 91.186.201.0/24 for now.

Thank you for also checking every IP in the list, I did not do this myself!


https://www.iplocation.net/ip-lookup
***
![image](https://github.com/SasukeFreestyle/XTLS-Iran-Reality/assets/2391403/1b0c2299-3fd2-4a50-b669-29a840e2075d)
https://whatismyipaddress.com
***

![image](https://github.com/SasukeFreestyle/XTLS-Iran-Reality/assets/2391403/72834c2e-92ae-4f31-9f23-6ee2dbfaa1a9)

**Comment by houmie** [comment]
Thank you. Yes that makes sense. :) 

If we are not 100% sure where an IP address comes from, it's better to block it.
