### ISSUE TITLE
is domain name a must ?/ is certificate needed for own domain?

### ISSUE THREAD

**Issue by yumeo-ch** [SasukeFreestyle/XTLS-Iran-Reality#3]
Hello, 
This configuration, without any domain name, worked good on Hamraavval yesterday, 
however this stopped working after 24 hours. 
I think this reality protocol works now only with a domain name that is certified, at least it's the case for irancell and hamra avval.
I recommend you to create a tutorial for doing it with domain name as well, 
i am unsuccesfully trying to add domain, but still doesn't work correctly (TLS handshake error)

- is installing Nginx a must ?

**Comment by yumeo-ch** [comment]
aha, I see. 
When we link a domain name to the server ? should we put this same domain name as dest in v2ray as well ?

**Comment by SasukeFreestyle** [comment]
The domain name is for your own IP/server, its optional meaning its not necessary.  so you don't have to remember your IP to your Xray server.

Destination ("dest:") is a target website that reality will steal TLS certificate from. This website must not be a blocked website in Iran.

**Comment by yumeo-ch** [comment]
then is it necessary to make a certificate with certbot ?
best regards.

**Comment by SasukeFreestyle** [comment]
No.

All you need to do is point / target xray reality to a website in "dest:".

The domain you own/buy does not need TLS/certbot.

**Comment by yumeo-ch** [comment]
Thank you, that completely answers my question. 
However still impossible to connect (tls error) with or without domain, from Irancell and Hamraye avval.
