### ISSUE TITLE
Custom rules not working

### ISSUE THREAD

**Issue by yumeo-ch** [SasukeFreestyle/XTLS-Iran-Reality#6]
When I try putting the custom rules to access Iranian websites, v2ray android gives me this error and the service doesn't start

: ```
infra/conf/serial: failed to parse json config > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ir > infra/conf: failed to load geosite: CATEGORY-IR > infra/conf: list not found in geosite.dat: CATEGORY-IR
04-28 xx:xx:00.856 D/com.v2ray.ang(28101): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ir > infra/conf: failed to load geosite: CATEGORY-IR > infra/conf: list not found in geosite.dat: CATEGORY-IR

```

**Comment by SasukeFreestyle** [comment]
Yeah some get this error, you can remove category-ir from the list and try and see if you can access Iranian sites without it.

```
geoip:private,
geosite:private,
geoip:ir
```

**Comment by yumeo-ch** [comment]
After few attempts, I found the origin of the problem.
v2rayng doesn't update automatically the geofiles at first install, 
what should be done is that the user should first go to the "gea asset files" settings and click on the little download cloud,
once files are updated, the user should force quit the app and clear cache and the apply the follwing settings :

```
geoip:private,
geosite:private,
geoip:ir,
geosite:category-ir
```
then everything works fine.
Maybe it's good idea to add these steps to the main tutorial :-) 
It's also a good idea to add in the beginning that it's hard to find a clean IP, and that users shouldn't buy ips from unknown non-mainstream providers (ovh ect.), because the small random sites that might have clean IPs might also be in the hand of the govt and they can close it at any moment and also monitor.

Thank you again, ur life saviour as it is one of the only protocols that works stable in the country now.

**Comment by SasukeFreestyle** [comment]
@yumeo-ch You are welcome friend and thank you. 

Reason I did not mention it is that for me I get this error when trying to download geoasset files. It has never worked for me.
![image](https://user-images.githubusercontent.com/2391403/235302692-8a745e3e-7479-4a79-a477-62f0b50bcb21.png)

I will add your steps to the guide and the clean-ip explanation.

Zan Zenedgi Azadi.
